services:
  postgres:
    container_name: "postgres"
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./my_taxi_postgres_data:/var/lib/postgresql/data
    networks:
      - pg-networks

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ming.com
      - PGADMIN_DEFAULT_PASSWORD=root
    networks:
      - pg-networks

networks:
  pg-networks:
    driver: bridge